# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from data.MCP import mcp_pb2 as data_dot_MCP_dot_mcp__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in data/MCP/mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NexusMCPStub(object):
    """Nexus MCP Service - High-performance gRPC interface for memory and tools
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEvent = channel.unary_unary(
                '/nexus.NexusMCP/AppendEvent',
                request_serializer=data_dot_MCP_dot_mcp__pb2.AppendEventRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.AppendEventResponse.FromString,
                _registered_method=True)
        self.GetRecentHistory = channel.unary_unary(
                '/nexus.NexusMCP/GetRecentHistory',
                request_serializer=data_dot_MCP_dot_mcp__pb2.GetHistoryRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.GetHistoryResponse.FromString,
                _registered_method=True)
        self.InsertNote = channel.unary_unary(
                '/nexus.NexusMCP/InsertNote',
                request_serializer=data_dot_MCP_dot_mcp__pb2.InsertNoteRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.NoteResponse.FromString,
                _registered_method=True)
        self.SearchNotes = channel.unary_unary(
                '/nexus.NexusMCP/SearchNotes',
                request_serializer=data_dot_MCP_dot_mcp__pb2.SearchRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.SearchNotesResponse.FromString,
                _registered_method=True)
        self.DeleteNote = channel.unary_unary(
                '/nexus.NexusMCP/DeleteNote',
                request_serializer=data_dot_MCP_dot_mcp__pb2.DeleteNoteRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListNotes = channel.unary_unary(
                '/nexus.NexusMCP/ListNotes',
                request_serializer=data_dot_MCP_dot_mcp__pb2.ListNotesRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.ListNotesResponse.FromString,
                _registered_method=True)
        self.SearchHistory = channel.unary_unary(
                '/nexus.NexusMCP/SearchHistory',
                request_serializer=data_dot_MCP_dot_mcp__pb2.SearchRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.SearchHistoryResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/nexus.NexusMCP/CallTool',
                request_serializer=data_dot_MCP_dot_mcp__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=data_dot_MCP_dot_mcp__pb2.ToolCallResponse.FromString,
                _registered_method=True)


class NexusMCPServicer(object):
    """Nexus MCP Service - High-performance gRPC interface for memory and tools
    """

    def AppendEvent(self, request, context):
        """Memory operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertNote(self, request, context):
        """Notes/Memory CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHistory(self, request, context):
        """Chat history search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Generic tool call (fallback for any tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NexusMCPServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvent,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.AppendEventRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.AppendEventResponse.SerializeToString,
            ),
            'GetRecentHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentHistory,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.GetHistoryRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.GetHistoryResponse.SerializeToString,
            ),
            'InsertNote': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertNote,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.InsertNoteRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.NoteResponse.SerializeToString,
            ),
            'SearchNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchNotes,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.SearchRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.SearchNotesResponse.SerializeToString,
            ),
            'DeleteNote': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNote,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.DeleteNoteRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.DeleteResponse.SerializeToString,
            ),
            'ListNotes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotes,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.ListNotesRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.ListNotesResponse.SerializeToString,
            ),
            'SearchHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHistory,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.SearchRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.SearchHistoryResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=data_dot_MCP_dot_mcp__pb2.ToolCallRequest.FromString,
                    response_serializer=data_dot_MCP_dot_mcp__pb2.ToolCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.NexusMCP', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.NexusMCP', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NexusMCP(object):
    """Nexus MCP Service - High-performance gRPC interface for memory and tools
    """

    @staticmethod
    def AppendEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/AppendEvent',
            data_dot_MCP_dot_mcp__pb2.AppendEventRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.AppendEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecentHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/GetRecentHistory',
            data_dot_MCP_dot_mcp__pb2.GetHistoryRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.GetHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/InsertNote',
            data_dot_MCP_dot_mcp__pb2.InsertNoteRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.NoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/SearchNotes',
            data_dot_MCP_dot_mcp__pb2.SearchRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.SearchNotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/DeleteNote',
            data_dot_MCP_dot_mcp__pb2.DeleteNoteRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/ListNotes',
            data_dot_MCP_dot_mcp__pb2.ListNotesRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.ListNotesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/SearchHistory',
            data_dot_MCP_dot_mcp__pb2.SearchRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.SearchHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.NexusMCP/CallTool',
            data_dot_MCP_dot_mcp__pb2.ToolCallRequest.SerializeToString,
            data_dot_MCP_dot_mcp__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
